name: VideoXML

on:
  schedule:
    - cron: '0 3 */2 * *'  # Run at 3am every 48 hours
  workflow_dispatch:

jobs:
  scrape_and_generate_epg:
    name: Scrape TV Programming and Generate EPG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytz

      - name: Run EPG Script
        run: |
          python py/videoxml.py > en/videoall.xml
        env:
          TZ: America/New_York

      - name: Pull latest changes before commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git diff --quiet || git stash --include-untracked
          git pull --rebase origin main

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update token"
          branch: main
          files: |
            en/videoall.xml
          allow_empty_commit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
